# Generated by Django 2.1.5 on 2019-05-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190504_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='random_user',
            field=models.TextField(default='Name'),
            preserve_default=False,
        ),
    ]
